#!/bin/sh -x
set -ue

opt_pid=0
pid=0
opt_command=0
command=""

while getopts p:h name
do
  case $name in
    p) opt_pid=1; pid=$OPTARG ;;
    h|?) cat <<-END >&2
	USAGE: alloc_lifetime { -p PID | command }
	e.g.: 
	  alloc_lifetime -p 12345
	  alloc_lifetime ls
	END
    exit 1
  esac
done

shift $(( OPTIND - 1 ))

if [ $opt_pid -eq 0 ]; then
	opt_command=1
	if [ "$*" = "" ]; then
		$0 -h
		exit
	fi
	command="$*"
fi

#################################
# --- Main Program, DTrace ---
#

### Define D Script
dtrace='
  #pragma D option quiet
 
  pid$target::malloc:return {
    self->lifetime[arg1] = timestamp
  } 
 
  pid$target::free:entry {
    @ = quantize((timestamp - self->lifetime[arg0]) / 1000000)
  } 

  tick-10s {
    exit(0)
  }
'

### Run DTrace
if [ $opt_command -eq 1 ]; then
	dtrace -x evaltime=exec -n "$dtrace" -c "$command" >&2
else
	dtrace -n "$dtrace" -p "$pid" >&2
fi

